GET http://localhost:3000/courses/courselist/AAS/170

###

GET http://localhost:3000/courses/courselist/AAS%20170

###

GET http://localhost:3000/courses/schedules

###

GET http://localhost:3000/courses/schedules/myname

###

POST http://localhost:3000/courses/schedules
Content-Type: application/json

{
    "name": "myname"
}